Hw2
================
2022-09-30

# Problem 1

## import data

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
raw_data = read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c"))
head(raw_data)
```

    ## # A tibble: 6 × 32
    ##   Division Line     Station…¹ Stati…² Stati…³ Route1 Route2 Route3 Route4 Route5
    ##   <chr>    <chr>    <chr>       <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 2 BMT      4 Avenue 25th St      40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## 3 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 4 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 5 BMT      4 Avenue 36th St      40.7   -74.0 N      R      <NA>   <NA>   <NA>  
    ## 6 BMT      4 Avenue 45th St      40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>  
    ## # … with 22 more variables: Route6 <chr>, Route7 <chr>, Route8 <chr>,
    ## #   Route9 <chr>, Route10 <chr>, Route11 <chr>, `Entrance Type` <chr>,
    ## #   Entry <chr>, `Exit Only` <chr>, Vending <chr>, Staffing <chr>,
    ## #   `Staff Hours` <chr>, ADA <lgl>, `ADA Notes` <chr>, `Free Crossover` <lgl>,
    ## #   `North South Street` <chr>, `East West Street` <chr>, Corner <chr>,
    ## #   `Entrance Latitude` <dbl>, `Entrance Longitude` <dbl>,
    ## #   `Station Location` <chr>, `Entrance Location` <chr>, and abbreviated …

``` r
nrow(raw_data)
```

    ## [1] 1868

``` r
ncol(raw_data)
```

    ## [1] 32

## clean data

``` r
data = raw_data%>%
  janitor::clean_names() %>% 
  select(line:entry,vending,ada) %>%
  mutate(
    entry = recode(entry, "YES" = TRUE, "NO" = FALSE),
    )
  
summary(data)
```

    ##      line           station_name       station_latitude station_longitude
    ##  Length:1868        Length:1868        Min.   :40.58    Min.   :-74.03   
    ##  Class :character   Class :character   1st Qu.:40.69    1st Qu.:-73.99   
    ##  Mode  :character   Mode  :character   Median :40.73    Median :-73.96   
    ##                                        Mean   :40.73    Mean   :-73.94   
    ##                                        3rd Qu.:40.77    3rd Qu.:-73.91   
    ##                                        Max.   :40.90    Max.   :-73.76   
    ##     route1             route2             route3             route4         
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##     route5             route6             route7             route8         
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##     route9            route10            route11          entrance_type     
    ##  Length:1868        Length:1868        Length:1868        Length:1868       
    ##  Class :character   Class :character   Class :character   Class :character  
    ##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
    ##                                                                             
    ##                                                                             
    ##                                                                             
    ##    entry           vending             ada         
    ##  Mode :logical   Length:1868        Mode :logical  
    ##  FALSE:115       Class :character   FALSE:1400     
    ##  TRUE :1753      Mode  :character   TRUE :468      
    ##                                                    
    ##                                                    
    ## 

The original dataset is a 1868 \* 32 dataset. It contains 1)The name and
location of the station of the entrances 2)the route that stop at the
stations 3)the stations’ entrance type 4)whether it is a entry or exit
only 5)whether there is a vending machine 6)the staffing condition
7)Whether there is free corssover 8)location of the entrance At first,
the data is not tidy.The type of the route variable are not the same.
The first step is to convert the type of route8-route11 to character.
And I used clean_names() to clean up the column names. Then I selected
the required columns and convert the entry variable to logical value.
The results is a 1868 \* 19 dataset

## How many distinct stations are there?

``` r
data %>%
  select(line, station_name)%>%
  distinct()%>%
  nrow()
```

    ## [1] 465

Answer: there are 465 distinct stations \## How many stations are ADA
compliant?

``` r
data %>%
  filter(ada == TRUE) %>%
  select(line,station_name) %>%
  distinct()%>%
  nrow()
```

    ## [1] 84

Answer: 84 stations are ADA compliant.

## What proportion of station entrances / exits without vending allow entrance?

``` r
data %>%
  filter(vending == "NO")%>%
  pull(entry)%>%
  mean()
```

    ## [1] 0.3770492

Answer: 37.7% of the entrances/exits without vending machine allow
entrance

## reformat the table to make route number and route name distinct variables

``` r
reformed_data <- data %>%
  pivot_longer(route1:route11,
               names_to = "route_number",
               values_to = "route_name") # reformat the data
reformed_data %>% 
  select(line,station_name,route_name)%>%
  filter(route_name == "A")%>%
  distinct()%>%
  nrow()  # stations that serve A train
```

    ## [1] 60

``` r
reformed_data %>%
  select(line,station_name,route_name,ada)%>%
  filter(route_name == "A")%>%
  filter(ada == TRUE)%>%
  distinct()%>%
  nrow() # total number of ADA compliant stations
```

    ## [1] 17

Answer: 60 distinct stations serve A train, 17 has ADA Compliant.

# Problem 2

## import data

``` r
raw_data2 <- read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
                        sheet = "Mr. Trash Wheel",
                        skip = 1)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`
    ## • `` -> `...17`

``` r
head(raw_data2)
```

    ## # A tibble: 6 × 17
    ##   Dumpster Month  Year Date                Weight (ton…¹ Volum…² Plast…³ Polys…⁴
    ##   <chr>    <chr> <dbl> <dttm>                      <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 1        May    2014 2014-05-16 00:00:00          4.31      18    1450    1820
    ## 2 2        May    2014 2014-05-16 00:00:00          2.74      13    1120    1030
    ## 3 3        May    2014 2014-05-16 00:00:00          3.45      15    2450    3100
    ## 4 4        May    2014 2014-05-17 00:00:00          3.1       15    2380    2730
    ## 5 5        May    2014 2014-05-17 00:00:00          4.06      18     980     870
    ## 6 6        May    2014 2014-05-20 00:00:00          2.71      13    1430    2140
    ## # … with 9 more variables: `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Grocery Bags` <dbl>, `Chip Bags` <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>, ...15 <chr>, ...16 <lgl>, ...17 <lgl>, and
    ## #   abbreviated variable names ¹​`Weight (tons)`, ²​`Volume (cubic yards)`,
    ## #   ³​`Plastic Bottles`, ⁴​Polystyrene

## clean data

``` r
data <- raw_data2 %>%
  janitor::clean_names()%>%
  select(1:14)%>% # remove useless columns
  na.omit()%>%  # remove non dumpster-specific rows
  rename("Dumpster number" = dumpster, 
         "Weight(tons)" = weight_tons,
         "Volume(cubic yards)" = volume_cubic_yards,
         "Number_of_plastic_Bottles" = plastic_bottles,
         "Number_of_Polystyrene" = polystyrene,
         "Number_of_Cigarette_Butts" = cigarette_butts,
         "Number_of_Grocery_bags" = grocery_bags,
         "Number_of_Chip_bags" = chip_bags,
         "Number_of_Sports_balls" = sports_balls
         ) 
data$Number_of_Sports_balls <- round (data$Number_of_Sports_balls, 0) # round the variable to the nearest integer.
data$Number_of_Sports_balls<- as.integer(data$Number_of_Sports_balls) # round the number of sports balls to the nearest integer and convert the type to integer. 
head(data)
```

    ## # A tibble: 6 × 14
    ##   Dumpster num…¹ month  year date                Weigh…² Volum…³ Numbe…⁴ Numbe…⁵
    ##   <chr>          <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 1              May    2014 2014-05-16 00:00:00    4.31      18    1450    1820
    ## 2 2              May    2014 2014-05-16 00:00:00    2.74      13    1120    1030
    ## 3 3              May    2014 2014-05-16 00:00:00    3.45      15    2450    3100
    ## 4 4              May    2014 2014-05-17 00:00:00    3.1       15    2380    2730
    ## 5 5              May    2014 2014-05-17 00:00:00    4.06      18     980     870
    ## 6 6              May    2014 2014-05-20 00:00:00    2.71      13    1430    2140
    ## # … with 6 more variables: Number_of_Cigarette_Butts <dbl>,
    ## #   glass_bottles <dbl>, Number_of_Grocery_bags <dbl>,
    ## #   Number_of_Chip_bags <dbl>, Number_of_Sports_balls <int>,
    ## #   homes_powered <dbl>, and abbreviated variable names ¹​`Dumpster number`,
    ## #   ²​`Weight(tons)`, ³​`Volume(cubic yards)`, ⁴​Number_of_plastic_Bottles,
    ## #   ⁵​Number_of_Polystyrene

## import Professor Trash Wheel data

``` r
raw_data3 <- read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
                        sheet = "Professor Trash Wheel",
                        skip = 1)
raw_data3
```

    ## # A tibble: 115 × 14
    ##    Dumpster Month       Year Date                Weigh…¹ Volum…² Plast…³ Polys…⁴
    ##       <dbl> <chr>      <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January     2017 2017-01-02 00:00:00    1.79      15    1950    6080
    ##  2        2 January     2017 2017-01-30 00:00:00    1.58      15    9540   11230
    ##  3       NA January T…    NA NA                     3.37      30   11490   17310
    ##  4        3 February    2017 2017-02-26 00:00:00    2.32      18    8350    9210
    ##  5        4 February    2017 2017-02-26 00:00:00    3.72      15    8590    1030
    ##  6        5 February    2017 2017-02-28 00:00:00    1.45      15    7830    9950
    ##  7       NA February …    NA NA                     7.49      48   24770   20190
    ##  8        6 March       2017 2017-03-30 00:00:00    1.71      15    8210   10340
    ##  9       NA March Tot…    NA NA                     1.71      15    8210   10340
    ## 10        7 April       2017 2017-04-01 00:00:00    1.82      15    9830   11020
    ## # … with 105 more rows, 6 more variables: `Cigarette Butts` <dbl>,
    ## #   `Glass Bottles` <dbl>, `Grocery Bags` <dbl>, `Chip Bags` <dbl>,
    ## #   `Sports Balls` <dbl>, `Homes Powered*` <dbl>, and abbreviated variable
    ## #   names ¹​`Weight (tons)`, ²​`Volume (cubic yards)`, ³​`Plastic Bottles`,
    ## #   ⁴​Polystyrene

## clean data

``` r
data2 <- raw_data3 %>%
  janitor::clean_names()%>%
  select(1:14)%>% # remove useless columns
  na.omit()%>%  # remove non dumpster-specific rows
  rename("Dumpster number" = dumpster, 
         "Weight(tons)" = weight_tons,
         "Volume(cubic yards)" = volume_cubic_yards,
        "Number_of_plastic_Bottles" = plastic_bottles,
         "Number_of_Polystyrene" = polystyrene,
         "Number_of_Cigarette_Butts" = cigarette_butts,
         "Number_of_Grocery_bags" = grocery_bags,
         "Number_of_Chip_bags" = chip_bags,
         "Number_of_Sports_balls" = sports_balls)
data2$'Dumpster number'<- as.character(data2$'Dumpster number')
data2$Number_of_Sports_balls <- round (data2$Number_of_Sports_balls, 0) # round the variable to the nearest integer.
data2$Number_of_Sports_balls <- as.integer(data2$Number_of_Sports_balls) # round the number of sports balls to the nearest integer and convert the type to integer. 
data2
```

    ## # A tibble: 71 × 14
    ##    Dumpster nu…¹ month  year date                Weigh…² Volum…³ Numbe…⁴ Numbe…⁵
    ##    <chr>         <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1             Janu…  2017 2017-01-02 00:00:00    1.79      15    1950    6080
    ##  2 2             Janu…  2017 2017-01-30 00:00:00    1.58      15    9540   11230
    ##  3 3             Febr…  2017 2017-02-26 00:00:00    2.32      18    8350    9210
    ##  4 4             Febr…  2017 2017-02-26 00:00:00    3.72      15    8590    1030
    ##  5 5             Febr…  2017 2017-02-28 00:00:00    1.45      15    7830    9950
    ##  6 6             March  2017 2017-03-30 00:00:00    1.71      15    8210   10340
    ##  7 7             April  2017 2017-04-01 00:00:00    1.82      15    9830   11020
    ##  8 8             April  2017 2017-04-20 00:00:00    2.37      15    9240    8760
    ##  9 9             May    2017 2017-05-10 00:00:00    2.64      15    9540    8810
    ## 10 10            May    2017 2017-05-26 00:00:00    2.78      15    8230    7800
    ## # … with 61 more rows, 6 more variables: Number_of_Cigarette_Butts <dbl>,
    ## #   glass_bottles <dbl>, Number_of_Grocery_bags <dbl>,
    ## #   Number_of_Chip_bags <dbl>, Number_of_Sports_balls <int>,
    ## #   homes_powered <dbl>, and abbreviated variable names ¹​`Dumpster number`,
    ## #   ²​`Weight(tons)`, ³​`Volume(cubic yards)`, ⁴​Number_of_plastic_Bottles,
    ## #   ⁵​Number_of_Polystyrene

## combine the dataset

``` r
data$trash_wheel_type <- "My Trash Wheel"
data2$trash_wheel_type <- "Professor Trash Wheel" # add new column
new_data <- full_join(data,data2) # combine two datasets
```

    ## Joining, by = c("Dumpster number", "month", "year", "date", "Weight(tons)",
    ## "Volume(cubic yards)", "Number_of_plastic_Bottles", "Number_of_Polystyrene",
    ## "Number_of_Cigarette_Butts", "glass_bottles", "Number_of_Grocery_bags",
    ## "Number_of_Chip_bags", "Number_of_Sports_balls", "homes_powered",
    ## "trash_wheel_type")

``` r
summary(new_data)
```

    ##  Dumpster number       month                year     
    ##  Length:524         Length:524         Min.   :2014  
    ##  Class :character   Class :character   1st Qu.:2016  
    ##  Mode  :character   Mode  :character   Median :2018  
    ##                                        Mean   :2017  
    ##                                        3rd Qu.:2019  
    ##                                        Max.   :2021  
    ##       date                         Weight(tons)   Volume(cubic yards)
    ##  Min.   :1900-01-20 00:00:00.00   Min.   :0.610   Min.   : 6.0       
    ##  1st Qu.:2016-04-30 00:00:00.00   1st Qu.:2.475   1st Qu.:15.0       
    ##  Median :2018-04-16 00:00:00.00   Median :3.090   Median :15.0       
    ##  Mean   :2017-09-06 07:52:40.30   Mean   :3.025   Mean   :15.3       
    ##  3rd Qu.:2019-06-12 00:00:00.00   3rd Qu.:3.572   3rd Qu.:15.0       
    ##  Max.   :2021-01-04 00:00:00.00   Max.   :5.620   Max.   :20.0       
    ##  Number_of_plastic_Bottles Number_of_Polystyrene Number_of_Cigarette_Butts
    ##  Min.   : 210              Min.   :  210         Min.   :   980           
    ##  1st Qu.:1075              1st Qu.:  990         1st Qu.:  5500           
    ##  Median :1980              Median : 2000         Median : 11000           
    ##  Mean   :2416              Mean   : 2460         Mean   : 23119           
    ##  3rd Qu.:2875              3rd Qu.: 3152         3rd Qu.: 28000           
    ##  Max.   :9830              Max.   :11528         Max.   :310000           
    ##  glass_bottles    Number_of_Grocery_bags Number_of_Chip_bags
    ##  Min.   :  0.00   Min.   :   50          Min.   :  180.0    
    ##  1st Qu.:  8.00   1st Qu.:  480          1st Qu.:  878.5    
    ##  Median : 18.00   Median :  890          Median : 1565.0    
    ##  Mean   : 21.02   Mean   : 1394          Mean   : 2584.0    
    ##  3rd Qu.: 29.50   3rd Qu.: 1752          3rd Qu.: 2760.0    
    ##  Max.   :110.00   Max.   :13450          Max.   :20100.0    
    ##  Number_of_Sports_balls homes_powered   trash_wheel_type  
    ##  Min.   : 0.00          Min.   : 0.00   Length:524        
    ##  1st Qu.: 3.00          1st Qu.:33.62   Class :character  
    ##  Median : 8.00          Median :48.83   Mode  :character  
    ##  Mean   :10.18          Mean   :43.49                     
    ##  3rd Qu.:14.00          3rd Qu.:57.17                     
    ##  Max.   :56.00          Max.   :93.67

Both the datasets contain the date of the transport time, weight, volume
and amount of each type of trash the dumpster transported. The datasets
also include the amount of homes which powered by electricity generated
by the trash. For example, they the column “Weight”, “Volume” provides
the weight and volume of trash each dumpster transported each
day.”Plastic_bottles”, “polystyrene” represents the amount of part of
the types of the trash disposed by dumpster.

## Information in the data

``` r
sum(data2$`Weight(tons)`)
```

    ## [1] 135.5

Answer: The total weight of trash collected by Professor Trash Wheel is
135.5 tons

``` r
filtered_data <- data %>%
  select(Number_of_Sports_balls, year)%>%
  filter(year == 2020)  #create a table store the amount of sports balls collected in each day in 2020.

sum(filtered_data$Number_of_Sports_balls)
```

    ## [1] 856

Answer: Number of sports balls collected by Mr. Trash Wheel in 2020 is
856.

# Problem 3

## import data

``` r
raw_data4 <- read.csv("data/pols-month.csv")
ncol(raw_data4)
```

    ## [1] 9

``` r
nrow(raw_data4)
```

    ## [1] 822

``` r
raw_data5 <- read.csv("data/snp.csv")
ncol(raw_data5)
```

    ## [1] 2

``` r
nrow(raw_data5)
```

    ## [1] 787

``` r
raw_data6 <- read.csv("data/unemployment.csv")
ncol(raw_data6)
```

    ## [1] 13

``` r
nrow(raw_data6)
```

    ## [1] 68

## clean pols-month data

``` r
pols_month_data <- raw_data4%>%
  janitor::clean_names()%>%
  separate(mon, into = c("year","month","day"),sep = "-" )%>%
  mutate(
    month = recode(month, "01" = "Jan","02" = "Feb", "03" = "Mar", "04" = "Apr",
                   "05" = "May", "06" = "Jun", "07" = "Jul", "08" = "Aug", 
                   "09" = "Sept", "10" = "Oct", "11" = "Nov", "12" = "Dec") #change the months' name
  )%>%
  mutate( 
    president = ifelse( prez_gop == 0, 'dem', 'gop'  ) # use president taking value gop and dem
    ) %>%
   select(-prez_dem,-prez_gop,-day)
head(pols_month_data)
```

    ##   year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ## 1 1947   Jan      23      51     253      23      45     198       dem
    ## 2 1947   Feb      23      51     253      23      45     198       dem
    ## 3 1947   Mar      23      51     253      23      45     198       dem
    ## 4 1947   Apr      23      51     253      23      45     198       dem
    ## 5 1947   May      23      51     253      23      45     198       dem
    ## 6 1947   Jun      23      51     253      23      45     198       dem

## clean snp data

``` r
snp_data <- raw_data5%>%
  janitor::clean_names()%>%
   separate(date, into = c("month","day","year"),sep = "/")
   snp_data$month <- as.integer(snp_data$month)
   snp_data$year <- as.integer(snp_data$year)
   snp_data$day <- as.integer(snp_data$day)
snp_data <-  snp_data %>%
  mutate(
    year = ifelse(year<=20,year+2000,year+1900)
  )%>%
  arrange(year,month)%>%
  mutate(
    month = recode(month, "1" = "Jan","2" = "Feb", "3" = "Mar", "4" = "Apr",
                   "5" = "May", "6" = "Jun", "7" = "Jul", "8" = "Aug", 
                   "9" = "Sept", "10" = "Oct", "11" = "Nov", "12" = "Dec")
  )%>%
  select(year, month, close)
head(snp_data)
```

    ##   year month close
    ## 1 1950   Jan 17.05
    ## 2 1950   Feb 17.22
    ## 3 1950   Mar 17.29
    ## 4 1950   Apr 17.96
    ## 5 1950   May 18.78
    ## 6 1950   Jun 17.69

``` r
tail(snp_data)
```

    ##     year month   close
    ## 782 2015   Feb 2104.50
    ## 783 2015   Mar 2067.89
    ## 784 2015   Apr 2085.51
    ## 785 2015   May 2107.39
    ## 786 2015   Jun 2063.11
    ## 787 2015   Jul 2079.65

## tidy unemployment data

``` r
unemployment_data <- raw_data6 %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan : dec, 
    names_to = "month",
    values_to = "unemployment"
  )%>%
  mutate(
    month = recode(month, "jan" = "Jan","feb" = "Feb", "mar" = "Mar", "apr" = "Apr",
                   "may" = "May", "jun" = "Jun", "jul" = "Jul", "aug" = "Aug", 
                   "sept" = "Sept", "oct" = "Oct", "nov" = "Nov", "dec" = "Dec")
  )

head(unemployment_data)
```

    ## # A tibble: 6 × 3
    ##    year month unemployment
    ##   <int> <chr>        <dbl>
    ## 1  1948 Jan            3.4
    ## 2  1948 Feb            3.8
    ## 3  1948 Mar            4  
    ## 4  1948 Apr            3.9
    ## 5  1948 May            3.5
    ## 6  1948 Jun            3.6

``` r
tail(unemployment_data)
```

    ## # A tibble: 6 × 3
    ##    year month unemployment
    ##   <int> <chr>        <dbl>
    ## 1  2015 Jul             NA
    ## 2  2015 Aug             NA
    ## 3  2015 sep             NA
    ## 4  2015 Oct             NA
    ## 5  2015 Nov             NA
    ## 6  2015 Dec             NA

## Join datasets

``` r
pols_month_data$year <- as.numeric(pols_month_data$year)# Convert character variable to numeric variable
Joined_data <- full_join(pols_month_data, snp_data) %>%
  full_join(unemployment_data)
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")

``` r
head(Joined_data)
```

    ##   year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ## 1 1947   Jan      23      51     253      23      45     198       dem    NA
    ## 2 1947   Feb      23      51     253      23      45     198       dem    NA
    ## 3 1947   Mar      23      51     253      23      45     198       dem    NA
    ## 4 1947   Apr      23      51     253      23      45     198       dem    NA
    ## 5 1947   May      23      51     253      23      45     198       dem    NA
    ## 6 1947   Jun      23      51     253      23      45     198       dem    NA
    ##   unemployment
    ## 1           NA
    ## 2           NA
    ## 3           NA
    ## 4           NA
    ## 5           NA
    ## 6           NA

The “pols_month” data is an 822 \* 9 datasets which records the number
of GOPs and DEMs in the government, the senate and the House of
Representatives from 1947 to 2015 and the party of the president of the
time. The snp data is a 787 \* 2 data which shows the Stock market
closing index at the beginning of every month from 1950 to 2015. And the
unemployment data is a 68 \* 13 data decribes the unemployment in each
month of the year from 1948 to 2015. The result dataset describes the
number of people of each party of the U.S. government, the Senate, the
House of Representatives, and the President’s party, the stock market
closing index, and the unemployment rate monthly from 1947 to
2015.Information of some months may not be included.
